In [1]:
medical_data = \
"""Marina Allison   ,27   ,   31.1 , 
#7010.0   ;Markus Valdez   ,   30, 
22.4,   #4050.0 ;Connie Ballard ,43 
,   25.3 , #12060.0 ;Darnell Weber   
,   35   , 20.6   , #7500.0;
Sylvie Charles   ,22, 22.1 
,#3022.0   ;   Vinay Padilla,24,   
26.9 ,#4620.0 ;Meredith Santiago, 51   , 
29.3 ,#16330.0;   Andre Mccarty, 
19,22.7 , #2900.0 ; 
Lorena Hodson ,65, 33.1 , #19370.0; 
Isaac Vu ,34, 24.8,   #7045.0"""

print(medical_data)

Marina Allison   ,27   ,   31.1 ,
#7010.0   ;Markus Valdez   ,   30,
22.4,   #4050.0 ;Connie Ballard ,43
,   25.3 , #12060.0 ;Darnell Weber
,   35   , 20.6   , #7500.0;
Sylvie Charles   ,22, 22.1
,#3022.0   ;   Vinay Padilla,24,
26.9 ,#4620.0 ;Meredith Santiago, 51   ,
29.3 ,#16330.0;   Andre Mccarty,
19,22.7 , #2900.0 ;
Lorena Hodson ,65, 33.1 , #19370.0;
Isaac Vu ,34, 24.8,   #7045.0

In [2]:
updated_medical_data = medical_data.replace("#", "$")
print(updated_medical_data)

Marina Allison   ,27   ,   31.1 ,
$7010.0   ;Markus Valdez   ,   30,
22.4,   $4050.0 ;Connie Ballard ,43
,   25.3 , $12060.0 ;Darnell Weber
,   35   , 20.6   , $7500.0;
Sylvie Charles   ,22, 22.1
,$3022.0   ;   Vinay Padilla,24,
26.9 ,$4620.0 ;Meredith Santiago, 51   ,
29.3 ,$16330.0;   Andre Mccarty,
19,22.7 , $2900.0 ;
Lorena Hodson ,65, 33.1 , $19370.0;
Isaac Vu ,34, 24.8,   $7045.0

In [6]:
num_records = 0

for character in updated_medical_data:
    if character == "$":
        num_records += 1
    
    print("There are " + str(num_records) + " medical records in the data.")

There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 0 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 1 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 2 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 3 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 4 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 5 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 6 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 7 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 8 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 9 medical records in the data.
There are 10 medical records in the data.
There are 10 medical records in the data.
There are 10 medical records in the data.
There are 10 medical records in the data.
There are 10 medical records in the data.
There are 10 medical records in the data.
There are 10 medical records in the data.

In [7]:
medical_data_split = updated_medical_data.split(";")
print(medical_data_split)

['Marina Allison   ,27   ,   31.1 , \n$7010.0   ', 'Markus Valdez   ,   30, \n22.4,   $4050.0 ', 'Connie Ballard ,43 \n,   25.3 , $12060.0 ', 'Darnell Weber   \n,   35   , 20.6   , $7500.0', '\nSylvie Charles   ,22, 22.1 \n,$3022.0   ', '   Vinay Padilla,24,   \n26.9 ,$4620.0 ', 'Meredith Santiago, 51   , \n29.3 ,$16330.0', '   Andre Mccarty, \n19,22.7 , $2900.0 ', ' \nLorena Hodson ,65, 33.1 , $19370.0', ' \nIsaac Vu ,34, 24.8,   $7045.0']

In [9]:
medical_records = []

for record in medical_data_split:
    medical_records.append(record.split(','))
    print(medical_records)

[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   ']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 ']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 ']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   ']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 ']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 '], ['Meredith Santiago', ' 51   ', ' \n29.3 ', '$16330.0']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 '], ['Meredith Santiago', ' 51   ', ' \n29.3 ', '$16330.0'], ['   Andre Mccarty', ' \n19', '22.7 ', ' $2900.0 ']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 '], ['Meredith Santiago', ' 51   ', ' \n29.3 ', '$16330.0'], ['   Andre Mccarty', ' \n19', '22.7 ', ' $2900.0 '], [' \nLorena Hodson ', '65', ' 33.1 ', ' $19370.0']]
[['Marina Allison   ', '27   ', '   31.1 ', ' \n$7010.0   '], ['Markus Valdez   ', '   30', ' \n22.4', '   $4050.0 '], ['Connie Ballard ', '43 \n', '   25.3 ', ' $12060.0 '], ['Darnell Weber   \n', '   35   ', ' 20.6   ', ' $7500.0'], ['\nSylvie Charles   ', '22', ' 22.1 \n', '$3022.0   '], ['   Vinay Padilla', '24', '   \n26.9 ', '$4620.0 '], ['Meredith Santiago', ' 51   ', ' \n29.3 ', '$16330.0'], ['   Andre Mccarty', ' \n19', '22.7 ', ' $2900.0 '], [' \nLorena Hodson ', '65', ' 33.1 ', ' $19370.0'], [' \nIsaac Vu ', '34', ' 24.8', '   $7045.0']]

In [10]:
medical_records_clean = []

for record in medical_records:
    record_clean = []
    
    for item in record:
        record_clean.append(item.strip())
        
        medical_records_clean.append(record_clean)
        print(medical_records_clean)

[['Marina Allison']]
[['Marina Allison', '27'], ['Marina Allison', '27']]
[['Marina Allison', '27', '31.1'], ['Marina Allison', '27', '31.1'], ['Marina Allison', '27', '31.1']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30'], ['Markus Valdez', '30']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4'], ['Markus Valdez', '30', '22.4'], ['Markus Valdez', '30', '22.4']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43'], ['Connie Ballard', '43']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3'], ['Connie Ballard', '43', '25.3'], ['Connie Ballard', '43', '25.3']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35'], ['Darnell Weber', '35']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6'], ['Darnell Weber', '35', '20.6'], ['Darnell Weber', '35', '20.6']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22'], ['Sylvie Charles', '22']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1'], ['Sylvie Charles', '22', '22.1'], ['Sylvie Charles', '22', '22.1']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24'], ['Vinay Padilla', '24']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9'], ['Vinay Padilla', '24', '26.9'], ['Vinay Padilla', '24', '26.9']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago', '51'], ['Meredith Santiago', '51']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago', '51', '29.3'], ['Meredith Santiago', '51', '29.3'], ['Meredith Santiago', '51', '29.3']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Meredith Santiago', '51', '29.3', '$16330.0']]
[['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Marina Allison', '27', '31.1', '$7010.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Markus Valdez', '30', '22.4', '$4050.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Connie Ballard', '43', '25.3', '$12060.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Darnell Weber', '35', '20.6', '$7500.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Sylvie Charles', '22', '22.1', '$3022.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Vinay Padilla', '24', '26.9', '$4620.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Meredith Santiago', '51', '29.3', '$16330.0'], ['Andre Mccarty']]

In [15]:
for record in medical_records_clean:
    print(record[0])

MARINA ALLISON
MARINA ALLISON
MARINA ALLISON
MARINA ALLISON
MARKUS VALDEZ
MARKUS VALDEZ
MARKUS VALDEZ
MARKUS VALDEZ
CONNIE BALLARD
CONNIE BALLARD
CONNIE BALLARD
CONNIE BALLARD
DARNELL WEBER
DARNELL WEBER
DARNELL WEBER
DARNELL WEBER
SYLVIE CHARLES
SYLVIE CHARLES
SYLVIE CHARLES
SYLVIE CHARLES
VINAY PADILLA
VINAY PADILLA
VINAY PADILLA
VINAY PADILLA
MEREDITH SANTIAGO
MEREDITH SANTIAGO
MEREDITH SANTIAGO
MEREDITH SANTIAGO
ANDRE MCCARTY
ANDRE MCCARTY
ANDRE MCCARTY
ANDRE MCCARTY
LORENA HODSON
LORENA HODSON
LORENA HODSON
LORENA HODSON
ISAAC VU
ISAAC VU
ISAAC VU
ISAAC VU

In [16]:
for record in medical_records_clean:
    record[0] = record[0].upper()
    print(record[0])

MARINA ALLISON
MARINA ALLISON
MARINA ALLISON
MARINA ALLISON
MARKUS VALDEZ
MARKUS VALDEZ
MARKUS VALDEZ
MARKUS VALDEZ
CONNIE BALLARD
CONNIE BALLARD
CONNIE BALLARD
CONNIE BALLARD
DARNELL WEBER
DARNELL WEBER
DARNELL WEBER
DARNELL WEBER
SYLVIE CHARLES
SYLVIE CHARLES
SYLVIE CHARLES
SYLVIE CHARLES
VINAY PADILLA
VINAY PADILLA
VINAY PADILLA
VINAY PADILLA
MEREDITH SANTIAGO
MEREDITH SANTIAGO
MEREDITH SANTIAGO
MEREDITH SANTIAGO
ANDRE MCCARTY
ANDRE MCCARTY
ANDRE MCCARTY
ANDRE MCCARTY
LORENA HODSON
LORENA HODSON
LORENA HODSON
LORENA HODSON
ISAAC VU
ISAAC VU
ISAAC VU
ISAAC VU

In [18]:
names = []

ages = []

bmis = []

insurance_costs = []

for record in medical_records_clean:
    names.append(record[0])
    ages.append(record[1])
    bmis.append(record[2])
    insurance_costs.append(record[3])
    
    print("Names: " + str(names))
    print("Ages: " + str(ages))
    print("BMI: " + str(bmis))
    print("Insurance Costs: " + str(insurance_costs))

Names: ['MARINA ALLISON']
Ages: ['27']
BMI: ['31.1']
Insurance Costs: ['$7010.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON']
Ages: ['27', '27']
BMI: ['31.1', '31.1']
Insurance Costs: ['$7010.0', '$7010.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON']
Ages: ['27', '27', '27']
BMI: ['31.1', '31.1', '31.1']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON']
Ages: ['27', '27', '27', '27']
BMI: ['31.1', '31.1', '31.1', '31.1']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ']
Ages: ['27', '27', '27', '27', '30']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ']
Ages: ['27', '27', '27', '27', '30', '30']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ']
Ages: ['27', '27', '27', '27', '30', '30', '30']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24', '24']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9', '26.9']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0', '$4620.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24', '24', '24']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9', '26.9', '26.9']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0', '$4620.0', '$4620.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'MEREDITH SANTIAGO']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24', '24', '24', '51']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9', '26.9', '26.9', '29.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0', '$4620.0', '$4620.0', '$16330.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24', '24', '24', '51', '51']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9', '26.9', '26.9', '29.3', '29.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0', '$4620.0', '$4620.0', '$16330.0', '$16330.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24', '24', '24', '51', '51', '51']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9', '26.9', '26.9', '29.3', '29.3', '29.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0', '$4620.0', '$4620.0', '$16330.0', '$16330.0', '$16330.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24', '24', '24', '51', '51', '51', '51']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9', '26.9', '26.9', '29.3', '29.3', '29.3', '29.3']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0', '$4620.0', '$4620.0', '$16330.0', '$16330.0', '$16330.0', '$16330.0']
Names: ['MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARINA ALLISON', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'MARKUS VALDEZ', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'CONNIE BALLARD', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'DARNELL WEBER', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'SYLVIE CHARLES', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'VINAY PADILLA', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO', 'MEREDITH SANTIAGO', 'ANDRE MCCARTY']
Ages: ['27', '27', '27', '27', '30', '30', '30', '30', '43', '43', '43', '43', '35', '35', '35', '35', '22', '22', '22', '22', '24', '24', '24', '24', '51', '51', '51', '51', '19']
BMI: ['31.1', '31.1', '31.1', '31.1', '22.4', '22.4', '22.4', '22.4', '25.3', '25.3', '25.3', '25.3', '20.6', '20.6', '20.6', '20.6', '22.1', '22.1', '22.1', '22.1', '26.9', '26.9', '26.9', '26.9', '29.3', '29.3', '29.3', '29.3', '22.7']
Insurance Costs: ['$7010.0', '$7010.0', '$7010.0', '$7010.0', '$4050.0', '$4050.0', '$4050.0', '$4050.0', '$12060.0', '$12060.0', '$12060.0', '$12060.0', '$7500.0', '$7500.0', '$7500.0', '$7500.0', '$3022.0', '$3022.0', '$3022.0', '$3022.0', '$4620.0', '$4620.0', '$4620.0', '$4620.0', '$16330.0', '$16330.0', '$16330.0', '$16330.0', '$2900.0']

In [21]:
total_bmi = 0
for bmi in bmis:
    total_bmi += float(bmi)
    
    average_bmi = total_bmi / len(bmis)
    print("Average BMI: " + str(average_bmi))

Average BMI: 0.7775000000000001
Average BMI: 1.5550000000000002
Average BMI: 2.3325000000000005
Average BMI: 3.1100000000000003
Average BMI: 3.6700000000000004
Average BMI: 4.23
Average BMI: 4.790000000000001
Average BMI: 5.3500000000000005
Average BMI: 5.982500000000001
Average BMI: 6.615
Average BMI: 7.2475000000000005
Average BMI: 7.880000000000001
Average BMI: 8.395000000000001
Average BMI: 8.910000000000002
Average BMI: 9.425000000000002
Average BMI: 9.940000000000003
Average BMI: 10.492500000000003
Average BMI: 11.045000000000005
Average BMI: 11.597500000000005
Average BMI: 12.150000000000006
Average BMI: 12.822500000000005
Average BMI: 13.495000000000005
Average BMI: 14.167500000000004
Average BMI: 14.840000000000003
Average BMI: 15.572500000000002
Average BMI: 16.305
Average BMI: 17.0375
Average BMI: 17.77
Average BMI: 18.3375
Average BMI: 18.905
Average BMI: 19.472500000000004
Average BMI: 20.040000000000003
Average BMI: 20.867500000000003
Average BMI: 21.695000000000004
Average BMI: 22.522500000000004
Average BMI: 23.350000000000005
Average BMI: 23.970000000000006
Average BMI: 24.590000000000003
Average BMI: 25.21
Average BMI: 25.830000000000002